### ISSUE TITLE
Add P5.js version?

### ISSUE THREAD

**Issue by VojtaStruhar** [Billocap/Donut-JS#2]
[P5.js](https://p5js.org/) is fairly popular framework for rendering cool stuff with javascript. I quickly adapted the code for their framewok - only changed the text rendering and resolved conflicting names. I think someone could find this interesting

https://editor.p5js.org/vojtechstruhar/sketches/pOHd-4grM

**Comment by Billocap** [comment]
That's really cool, it's nice to see this old project in a new engine.
If you are looking for a challenge you could convert it to ray marching. I think that could make the code even smaller.

**Comment by VojtaStruhar** [comment]
That could be actually pretty cool 🤔 P5 can do some shaders. Thanks for the suggestion
